### PR TITLE
Remove lib/bin-like sections from workspace Cargo.toml

### LINKED ISSUE #57: Sibling crates cannot be resolved on import
I noticed that when doing the following

1. Clone repo
2. Add `bevy_editor_camera` to `bevy_editor`s `Cargo.toml`
3. Import `bevy_editor_camera::*` in the `bevy_editor/src/main.rs` file
4. `cargo run` from the root path of the project

> [!NOTE]
> This happens with any sibling crate not just `bevy_editor_camera`.

the project fails to run due to unresolved dependencies.

```
error[E0432]: unresolved import `bevy_editor_camera`
  --> crates/bevy_editor/src/main.rs:15:5
   |
15 | use bevy_editor_camera::*;
   |     ^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `bevy_editor_camera`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `bevy_editor_prototypes` (bin "bevy_editor_standalone") due to 1 previous error
```

If you instead `cargo run` from within the `bevy_editor` crate itself the unresolved dependency issue is gone.
The issue here is that LSP servers still can't resolve the dependencies since their root is the workspace root.

So this seems like a configuration issue of some sort.

### PR DESCRIPTION
**Pull request by MiniaczQ**
Fixes #57 while still keeping everything as workspace members.
Alternative to #58

Added `bevy_editor_camera` dependency in `bevy_editor` and ran `cargo run` to make sure it works.
When/if we get more binaries we'll need to use the `--bin` flag

### CODE REVIEW

**Review by Dokkae6949 — APPROVED** [review]

File: crates/bevy_editor/src/main.rs [hunk 1]
```diff
@@ -12,8 +12,10 @@
 //! - Finally, it will be a standalone application that communicates with a running Bevy game via the Bevy Remote Protocol.
 
 use bevy::prelude::*;
+use bevy_editor_camera::*;
 
 fn main() {
+    add(1, 2);
```
Comment (Atlas16A) [inline crates/bevy_editor/src/main.rs:18]: remove the test func you did here

**Review by Atlas16A — CHANGES_REQUESTED** [review]

File: crates/bevy_editor/src/main.rs (hunk 1 above)
Comment (MiniaczQ) [reply crates/bevy_editor/src/main.rs:18]: Gotta keep it, otherwise we have unused imports (bevy_editor_camera)

Comment (MiniaczQ) [reply crates/bevy_editor/src/main.rs:18]: Or i can do a #[allow(...)]

Comment (Dokkae6949) [reply crates/bevy_editor/src/main.rs:18]: I suppose you can just remove the import as well since it's been tested and works now anyways. No need to keep it

**Review by Atlas16A — APPROVED** [review]

**Review by Dokkae6949 — APPROVED** [review]
